---
- name: Configuration for all servers
  hosts: all
  become: true

  roles:
    - common

- name: Configuration of postgreSQL
  hosts: app
  become: true

  roles:
    - postgresql
    - app

- name: Configuration of web server
  hosts: web
  become: true

  roles:
    - web